### ISSUE TITLE
Spotify “end session” command through Sonos api?

### ISSUE THREAD

**Issue by Nayhtohn** [hankhank10/vinylemulator#17]
I’m wondering if you can help with an issue I’m running into:

When I have a queue setup from the Sonos app the emulator works fine, but when I start a song from the Spotify app it doesn’t work and I have to go into the Sonos app and press “end session” before the emulator can work.

I can’t see on the Sonos api a command for end session, and clearqueue doesn’t seem to work - do you know if such a command exists? Or how I can watch the api command line when I press a button in the app to see what it tells the system to do?

Thanks,
Ben

**Comment by hankhank10** [comment]
Hi Ben, happy to help you debug this.

For starters, please could you stop the code running through pm2 (pm2 stop readnfc) if you have it running that way. Then manually run the code (python readnfc.py) and report back (a) what version you are running and (b) what error code you get when trying to tap a tag in this way.

Thanks

**Comment by Nayhtohn** [comment]
I have the following:
A) Script version Alpha 0.9.3...
B) When I present a tag I get:
"Read from NFC tag: spotify:album:7sYd6KDHefklNf94RmND8g
Detected spotify service request
Clearing Sonos Queue
Fetching URL via HTTP: http://localhost:5005/Living Room/spotify/now/spotify/album/7sYd6KDHefklNf94RmND8g
Error code returned from Sonos API"

When i press "End session" in the sonos app in my phone, the tag works as normal

Thanks,

Ben

**Comment by Nayhtohn** [comment]
From the Sonos API:
  | "Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.addURIToQueue (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:616:15)\n    at promise.then (/home/pi/node-sonos-http-api/lib/actions/spotify.js:37:33)"
-- | --
