### ISSUE TITLE
500 error when retrieving albums

### ISSUE THREAD

**Issue by DJT1423** [hankhank10/vinylemulator#30]
I have been running your wonderful program for a few years no with no issues. Suddenly my NFC tags have stopped calling up Spotify music. The Sonos API seems to be OK when I access http://myPi_IPAddress:5005/  Also, I can control Spotify on my Sonos with the http://myPi_IPAddress:5005/playpause command.

However, if I try playing an album on a windows machine with a web browser, for example: http://myPi_IPAddress:5005/Lounge/spotify/now/spotify:album:12n11cgnpjXKLeqrnIERoS as in your John Grant example, I receive this error:
{"status":"error","error":"Got status 500 when invoking /MediaRenderer/AVTransport/Control","stack":"Error: Got status 500 when invoking /MediaRenderer/AVTransport/Control\n    at Object.invoke (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/helpers/soap.js:99:10)\n    at Player.addURIToQueue (/home/pi/node-sonos-http-api/node_modules/sonos-discovery/lib/models/Player.js:616:15)\n    at promise.then (/home/pi/node-sonos-http-api/lib/actions/spotify.js:37:33)"}

Any thoughts as to what may be happening? By the way, I am still running "Buster" on this Pi.
Thanks, David T

**Comment by thesquib** [comment]
Hey David, I've been running everything just fine until a few weeks ago and now I'm in the same boat as you! Did you ever resolve this?

**Comment by DJT1423** [comment]
I never figured out the issue, but I found I had a backup SD card with my original install, and that saved me. Sorry

David
________________________________

**Comment by thesquib** [comment]
Thanks! So you do have it working? That's good to know
